### ISSUE TITLE
Accents in link words

### ISSUE THREAD

**Issue by lschwetlick** [lschwetlick/ADD-wiki#1]
bug, when the link word has an accent in it. test case is "france"

**Comment by chrisma** [comment]
Error message returned by the Wikipedia API:

> Bad title \"Michel_Debr%C3%A9\"

Problem with how accents are represented in query string. Query string contains  `page=Michel_Debr%25C3%25A9`

[https://en.wikipedia.org/w/api.php?action=parse&format=json&page=Michel_Debr%C3%A9&redirects=1&prop=text&section=0&disablelimitreport=1&disableeditsection=1&disabletoc=1&noimages=1](https://en.wikipedia.org/w/api.php?action=parse&format=json&page=Michel_Debr%C3%A9&redirects=1&prop=text&section=0&disablelimitreport=1&disableeditsection=1&disabletoc=1&noimages=1) works fine

The query string is double url-encoded. The href attr from the Wikipedia API is already encoded, we encode it a second time in the `$.param(params)` call.

```
> decodeURI("Michel_Debr%C3%A9")
<- "Michel_Debré"
```
