### ISSUE TITLE
Links to non-wikipedia sites should be ignored

### ISSUE THREAD

**Issue by lschwetlick** [lschwetlick/ADD-wiki#9]
Test case:
- musical notation

**Comment by chrisma** [comment]
I cannot reproduce this failure. Possibly the Wikipedia page changed.
I get the following chain: `Musical Notation` -> `Photocopier` -> `Duplicating machines` -> `Fanzine`

**Comment by lschwetlick** [comment]
Try in Heavy mode. "Aurally" is wiktionary link

**Comment by chrisma** [comment]
Ah, thanks. link goes to `wikt:aurally`.
All links that have a namespace, i.e. anything before an `:` (pointing outside of Wikipedia) should be ignored.

**Comment by lschwetlick** [comment]
Fixed for add level 2. Dont have test case for add level 1, but added code for that also.
